services:
  scraper:
    build: .
    container_name: scraper
    restart: unless-stopped
    shm_size: "1g"
    ports:
      - "8000:8000"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - server-network

networks:
  server-network:
    external: true
